spring:
  profiles:
    active:
      - dev

---
server: 
  port: 7003

spring:
  profiles: dev
  application:
    name: microservice-consumer-config-client

eureka:
  client:
    register-with-eureka: false
    service-url: 
      defaultZone: http://eureka9030.com:9030/eureka/,http://eureka9020.com:9020/eureka/,http://eureka9010.com:9010/eureka/

---
server: 
  port: 7004

spring:
  profiles: test
  application:
    name: microservice-consumer-config-client

eureka:
  client:
    register-with-eureka: false
    service-url: 
      defaultZone: http://eureka9030.com:9030/eureka/,http://eureka9020.com:9020/eureka/,http://eureka9010.com:9010/eureka/